version: '3'

services:
  web:
    image: hackers/faces
    build:
      context: ..
    command: ./wait.sh -s db:5432 -- ./run.sh python manage.py runserver 0.0.0.0:8000
    ports:
      - 80:8000

  db:
    image: postgres