# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 20:45
from __future__ import unicode_literals

import common.fields
import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', common.fields.SlugPkField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('alias', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(choices=[('Beacon', 'Beacon'), ('NFC', 'NFC'), ('RFID', 'RFID')], max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            bases=(common.models.DateTimeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ThingMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Thing')),
            ],
            bases=(common.models.DateTimeMixin, models.Model),
        ),
    ]
