# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='type',
            field=models.CharField(choices=[('BEACON', 'BEACON'), ('NFC', 'NFC'), ('RFID', 'RFID')], max_length=200),
        ),
    ]
