# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 19:07
from __future__ import unicode_literals

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_id', models.CharField(max_length=150)),
                ('face_image', models.ImageField(upload_to='')),
            ],
            bases=(common.models.DateTimeMixin, models.Model),
        ),
    ]
