# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='face_name',
            field=models.CharField(default='derek', max_length=150),
            preserve_default=False,
        ),
    ]
