# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0002_face_face_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='unknown',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='face',
            name='face_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
